# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 22:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trans_type', models.CharField(choices=[('add', 'credit'), ('subtract', 'debit')], default='debit', max_length=6)),
                ('trans_time', models.DateTimeField(auto_now_add=True)),
                ('trans_note', models.TextField(max_length=60)),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
