# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='trans_type',
            field=models.CharField(choices=[('add', 'credit'), ('subtract', 'debit')], default='debit', max_length=8),
        ),
    ]
