# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_auto_20160620_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttransaction',
            old_name='account_no',
            new_name='customer',
        ),
    ]
