# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_auto_20160621_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='trans_type',
            field=models.CharField(choices=[('Money in', 'credit'), ('Money out', 'debit')], default='debit', max_length=8),
        ),
    ]
