# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_auto_20160621_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttransaction',
            options={'ordering': ['-trans_time']},
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='trans_type',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='debit', max_length=8),
        ),
    ]
