# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_auto_20160622_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='trans_type',
            field=models.CharField(choices=[('Credit', 'credit'), ('Debit', 'debit')], default='debit', max_length=8),
        ),
    ]
