# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_auto_20160622_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='trans_type',
            field=models.CharField(choices=[('+', 'Credit'), ('-', 'Debit')], default='-', max_length=8),
        ),
    ]
