# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0010_auto_20160622_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='trans_note',
            field=models.CharField(max_length=30),
        ),
    ]
